version: '3.8'

services:
  # Service for installing dependencies
  install:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm install && ls -la /app/node_modules && npm run build"

  # Main web service to start the app
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEW_RELIC_LICENSE_KEY: 'sdfasdfasdfsdfasdfasdf'
      NEW_RELIC_APP_NAME: 'React_next_app_1'
      NODE_OPTIONS: '-r @newrelic/next'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - install
    command: bash -c "npm start"
