version: '3.8'

services:
  # Service for installing dependencies
  install:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm install && ls -la /app/node_modules && npm run build"

  # Main web service to start the app
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_NEW_RELIC_LICENSE_KEY: 'YOUR_KEY'
      NEXT_PUBLIC_NEW_RELIC_APP_NAME: 'APM_AND_BROWSER_EXAMPLE'
      NEW_RELIC_LICENSE_KEY: 'YOUR_KEY'
      NEW_RELIC_APP_NAME: 'APM_AND_BROWSER_EXAMPLE'
      NODE_OPTIONS: '--loader newrelic/esm-loader.mjs -r newrelic'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - install
    command: bash -c "npm start"
